### PR TITLE
Allow symlinks to be overwritten

### PR DESCRIPTION
**Pull request by xDarksome**
## Synopsis

Currently, regular files can be overwritten without a problem, but symlinks can not.

## Solution

Make `CreateSymlink` behavior similar to `CreateFile`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has type and `k::` labels applied
- Before [review][l:4]:
    - [x] Documentation is updated (if required)
    - [x] Tests are updated (if required)
    - [x] Changes conform [code style][l:2]
    - [x] [CHANGELOG entry][l:3] is added (if required)
    - [x] FCM (final commit message) is posted or updated
    - [x] [Draft mode][l:1] is removed
- [x] [Review][l:4] is completed and changes are approved
    - [x] FCM (final commit message) is approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

### CODE REVIEW

**Comment by xDarksome** [comment]
FCM
---
```
Allow symlinks to be overwritten (#6)
```

**Review by tyranron — CHANGES_REQUESTED** [review]
@xDarksome symlink overriding should be atomic. This is vital for our use case.

See: https://blog.moertel.com/posts/2005-08-22-how-to-change-symlinks-atomically.html

**Comment by tyranron** [comment]
As for Rust version, I'll made a change in `main` shortly.

**Comment by xDarksome** [comment]
@tyranron so, I digged a little bit further and it seems that cross-device atomic move/copy is not possible for symlinks.

`std::fs::copy` works only with regular files.

I did `strace` on `mv` and `cp -P` and they both fall back to:

```
unlink
symlink
```

I suggest we make a local tmp directory inside our `root` directory which is not accessible to write via API, and auto clean it on each startup.

The overall directory structure would be something like:
```
/{root}/
     -> data/
     -> tmp/
```

**Comment by tyranron** [comment]
@xDarksome ok then.

**Pull request merged**
